# This file enables the Travis continuous integration system, which
# automatically builds and tests joda-time for each GitHub commit or 
# pull request on three separate JDKs.
#
# For more information, see https://travis-ci.org

sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/time
# install
install:
  - mvn --version
script:
  - mvn install -e -B
# deploy website
deploy:
  provider: script
  script: travis_wait 40 mvn site-deploy -e -B --settings .github/maven-settings.xml
  on:
    jdk: "oraclejdk8"
    tags: true
    condition: "$TRAVIS_TAG =~ ^v.*$"
env:
  global:
    secure: UK9A4eHPOP6XkYbST1kpv3gVEZTBqp79eCF0nqpXejbXihY58MNVZ0aGt8IM/ZThO/UoK+AxWjaSLljE2Neo4ehxvRHsRG0bIhAoCBUjP6f6vuMYTZlRNb9W+NM3RjXvrQGnCM3PTckWaFQ6i5Ny4e1GuETSdh96Yk7WNn6DMJM=
